#pragma once
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <map>
#include <cctype>
#include <algorithm>
#include <iomanip>
#include <locale>
#include <codecvt>
#include <sstream>
#include <set>

using std::cout;
using std::endl;
using std::string;
using std::ifstream;
using std::vector;
using std::map;
using std::sort;
using std::pair;
using std::setw;
using std::left;
using std::wstringstream;
using std::wifstream;
using std::wcout;
using std::wstring;
using std::wistringstream;
using std::getline;
using std::pair;
using std::wofstream;
using std::set;